name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create and push release branch
        run: |
          RELEASE_VERSION=${{ github.event.inputs.release_version }}
          BRANCH_NAME="release-${RELEASE_VERSION}"
          git checkout -b $BRANCH_NAME
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $BRANCH_NAME
