name: 'Create Release Branch'
description: 'Creates a new release branch in the repository.'
inputs:
  release_version:
    description: 'Release version (e.g., 1.0.0)'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create release branch
      shell: bash
      run: |
        RELEASE_VERSION=${{ inputs.release_version }}
        BRANCH_NAME="release-${RELEASE_VERSION}"
        git checkout -b $BRANCH_NAME
        git push https://x-access-token:${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }} $BRANCH_NAME
